# Generated by Django 3.2.19 on 2023-07-29 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='games/')),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_category', models.CharField(choices=[('Action', 'Action'), ('Sport', 'Sport'), ('Horror', 'Horror'), ('Cooking', 'Cooking'), ('Puzzle', 'Puzzle')], default='Action', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name', 'price', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='GameInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VGPapp.game')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_state', models.CharField(choices=[('Ordered', 'Ordered'), ('Delivered', 'Delivered')], default='Ordered', max_length=20)),
                ('buyerName', models.CharField(max_length=50)),
                ('delivery_address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=100)),
                ('totalPrice', models.IntegerField(default=0)),
                ('games', models.ManyToManyField(through='VGPapp.GameInOrder', to='VGPapp.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gameinorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VGPapp.order'),
        ),
        migrations.CreateModel(
            name='GameInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VGPapp.cart')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VGPapp.game')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='games',
            field=models.ManyToManyField(through='VGPapp.GameInCart', to='VGPapp.Game'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
